import { useState } from "react";
import { Card, CardContent, CardHeader, CardTitle, CardDescription } from "@/components/ui/card";
import { Button } from "@/components/ui/button";
import { Badge } from "@/components/ui/badge";
import { Tabs, TabsContent, TabsList, TabsTrigger } from "@/components/ui/tabs";
import { ScrollArea } from "@/components/ui/scroll-area";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Switch } from "@/components/ui/switch";
import { 
  Download, 
  Copy, 
  Check, 
  FileJson, 
  FileSpreadsheet, 
  Code2,
  FlaskConical,
  Fingerprint,
  RefreshCw,
  BookOpen,
  ExternalLink,
  Sparkles
} from "lucide-react";
import { toast } from "sonner";

interface ResearchModeExportProps {
  simulationData: any;
  neurons: string[];
  stimulus: { type: string; value: number };
  duration: number;
}

export function ResearchModeExport({ 
  simulationData, 
  neurons, 
  stimulus, 
  duration 
}: ResearchModeExportProps) {
  const [copiedCode, setCopiedCode] = useState<string | null>(null);
  const [seed, setSeed] = useState(() => Math.floor(Math.random() * 1000000));
  const [includeRawData, setIncludeRawData] = useState(true);
  const [includeMetadata, setIncludeMetadata] = useState(true);

  const generateSeed = () => {
    const newSeed = Math.floor(Math.random() * 1000000);
    setSeed(newSeed);
    toast.success("New reproducibility seed generated", {
      description: `Seed: ${newSeed}`
    });
  };

  const copyToClipboard = (text: string, id: string) => {
    navigator.clipboard.writeText(text);
    setCopiedCode(id);
    toast.success("Copied to clipboard!");
    setTimeout(() => setCopiedCode(null), 2000);
  };

  // Generate CSV data
  const generateCSV = () => {
    const headers = ["timestamp_ms", "neuron_id", "neuron_type", "membrane_potential", "firing_event", "activation_level"];
    const rows: string[] = [headers.join(",")];

    if (simulationData?.results?.neural_activity) {
      simulationData.results.neural_activity.forEach((neuron: any) => {
        const activityTrace = neuron.activity_trace || [];
        const spikeTimes = new Set(neuron.spike_times_ms || []);
        
        activityTrace.forEach((activation: number, i: number) => {
          const timestamp = (i / activityTrace.length) * duration;
          rows.push([
            timestamp.toFixed(2),
            neuron.neuron_id,
            neuron.type || "unknown",
            (neuron.avg_membrane_potential || "-65mV").replace("mV", ""),
            spikeTimes.has(Math.round(timestamp)) ? "1" : "0",
            activation.toFixed(4)
          ].join(","));
        });
      });
    }

    return rows.join("\n");
  };

  // Generate JSON export
  const generateJSON = () => {
    const exportData: any = {
      metadata: {
        export_version: "1.0",
        exported_at: new Date().toISOString(),
        reproducibility_seed: seed,
        platform: "OpenWorm WormQuest",
        tagline: "Learn from the lowly!"
      },
      parameters: {
        neurons: neurons,
        stimulus: stimulus,
        duration_ms: duration,
        include_physics: true
      }
    };

    if (includeRawData) {
      exportData.results = simulationData?.results || {};
    }

    if (includeMetadata) {
      exportData.summary = {
        total_spikes: simulationData?.results?.neural_activity?.reduce(
          (sum: number, n: any) => sum + (n.firing_events || 0), 0
        ) || 0,
        behavior_prediction: simulationData?.results?.behavior_prediction,
        confidence: simulationData?.results?.confidence,
        compute_time_ms: simulationData?.compute_time_ms
      };
    }

    return JSON.stringify(exportData, null, 2);
  };

  // Generate Python notebook code
  const generatePythonNotebook = () => {
    return `# OpenWorm Neural Simulation Analysis
# "Learn from the lowly!"
# Generated by WormQuest Research Mode
# Reproducibility Seed: ${seed}

import json
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

# Simulation Parameters
NEURONS = ${JSON.stringify(neurons)}
STIMULUS_TYPE = "${stimulus.type}"
STIMULUS_VALUE = ${stimulus.value}
DURATION_MS = ${duration}
SEED = ${seed}

# Set random seed for reproducibility
np.random.seed(SEED)

# Load simulation data (paste your JSON export here)
simulation_data = '''
${generateJSON()}
'''

data = json.loads(simulation_data)

# Extract neural activity
neural_activity = data.get('results', {}).get('neural_activity', [])

# Create DataFrame for analysis
records = []
for neuron in neural_activity:
    records.append({
        'neuron_id': neuron.get('neuron_id'),
        'type': neuron.get('type'),
        'peak_activation': float(neuron.get('peak_activation', 0)),
        'firing_events': neuron.get('firing_events', 0),
        'firing_rate_hz': neuron.get('firing_rate_hz', 0)
    })

df = pd.DataFrame(records)
print("Neural Activity Summary:")
print(df)

# Visualization: Spike Raster Plot
fig, axes = plt.subplots(2, 2, figsize=(14, 10))

# 1. Firing Rate Comparison
ax1 = axes[0, 0]
colors = {'sensory': '#22c55e', 'interneuron': '#3b82f6', 'motor': '#ef4444'}
bar_colors = [colors.get(t, '#888') for t in df['type']]
ax1.barh(df['neuron_id'], df['firing_rate_hz'], color=bar_colors)
ax1.set_xlabel('Firing Rate (Hz)')
ax1.set_title('Firing Rate by Neuron')

# 2. Peak Activation
ax2 = axes[0, 1]
ax2.bar(df['neuron_id'], df['peak_activation'], color=bar_colors)
ax2.set_ylabel('Peak Activation')
ax2.set_title('Peak Activation by Neuron')
ax2.tick_params(axis='x', rotation=45)

# 3. Neuron Type Distribution
ax3 = axes[1, 0]
type_counts = df['type'].value_counts()
ax3.pie(type_counts.values, labels=type_counts.index, autopct='%1.1f%%',
        colors=[colors.get(t, '#888') for t in type_counts.index])
ax3.set_title('Neuron Type Distribution')

# 4. Total Spikes by Type
ax4 = axes[1, 1]
spikes_by_type = df.groupby('type')['firing_events'].sum()
ax4.bar(spikes_by_type.index, spikes_by_type.values,
        color=[colors.get(t, '#888') for t in spikes_by_type.index])
ax4.set_ylabel('Total Spikes')
ax4.set_title('Total Spikes by Neuron Type')

plt.tight_layout()
plt.savefig(f'openworm_analysis_seed_{SEED}.png', dpi=150)
plt.show()

# Behavior Prediction
behavior = data.get('summary', {}).get('behavior_prediction', 'unknown')
confidence = data.get('summary', {}).get('confidence', 0)
print(f"\\nBehavior Prediction: {behavior} (confidence: {confidence:.2%})")

# Citation
print("\\n--- Citation ---")
print("OpenWorm Project. WormQuest Neural Simulation Platform.")
print(f"Simulation conducted with seed {SEED} on {data['metadata']['exported_at']}")
print("https://openworm.org | 'Learn from the lowly!'")
`;
  };

  // Generate R script
  const generateRScript = () => {
    return `# OpenWorm Neural Simulation Analysis
# "Learn from the lowly!"
# Reproducibility Seed: ${seed}

library(jsonlite)
library(ggplot2)
library(dplyr)

# Set seed for reproducibility
set.seed(${seed})

# Simulation Parameters
neurons <- c(${neurons.map(n => `"${n}"`).join(", ")})
stimulus_type <- "${stimulus.type}"
stimulus_value <- ${stimulus.value}
duration_ms <- ${duration}

# Load data (save JSON export as 'simulation_data.json')
data <- fromJSON("simulation_data.json")

# Extract neural activity
neural_df <- as.data.frame(data$results$neural_activity)

# Summary statistics
cat("Neural Activity Summary:\\n")
print(summary(neural_df))

# Visualization
p1 <- ggplot(neural_df, aes(x = neuron_id, y = firing_rate_hz, fill = type)) +
  geom_bar(stat = "identity") +
  scale_fill_manual(values = c(
    "sensory" = "#22c55e",
    "interneuron" = "#3b82f6", 
    "motor" = "#ef4444"
  )) +
  theme_minimal() +
  labs(title = "Firing Rate by Neuron",
       subtitle = paste("Seed:", ${seed}),
       x = "Neuron", y = "Firing Rate (Hz)")

ggsave(paste0("openworm_analysis_seed_${seed}.png"), p1, width = 10, height = 6)

cat("\\nAnalysis complete. Plot saved.\\n")
cat("'Learn from the lowly!' - OpenWorm Project\\n")
`;
  };

  const downloadFile = (content: string, filename: string, mimeType: string) => {
    const blob = new Blob([content], { type: mimeType });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = filename;
    document.body.appendChild(a);
    a.click();
    document.body.removeChild(a);
    URL.revokeObjectURL(url);
    toast.success(`Downloaded ${filename}`);
  };

  return (
    <Card className="border-2 border-foreground/20">
      <CardHeader className="pb-3">
        <div className="flex items-center justify-between">
          <div>
            <CardTitle className="flex items-center gap-2 text-lg">
              <FlaskConical className="w-5 h-5 text-primary" />
              Research Mode
            </CardTitle>
            <CardDescription>
              Export data for publication and reproducible research
            </CardDescription>
          </div>
          <Badge variant="outline" className="gap-1 text-xs">
            <Sparkles className="w-3 h-3" />
            Learn from the lowly!
          </Badge>
        </div>
      </CardHeader>
      <CardContent className="space-y-4">
        {/* Reproducibility Seed */}
        <div className="flex items-center gap-3 p-3 bg-muted/50 rounded-lg">
          <Fingerprint className="w-5 h-5 text-primary" />
          <div className="flex-1">
            <Label className="text-xs font-bold">Reproducibility Seed</Label>
            <div className="flex items-center gap-2 mt-1">
              <Input 
                value={seed} 
                onChange={(e) => setSeed(parseInt(e.target.value) || 0)}
                className="h-8 w-32 font-mono text-sm"
              />
              <Button variant="ghost" size="sm" onClick={generateSeed}>
                <RefreshCw className="w-4 h-4" />
              </Button>
              <Button 
                variant="ghost" 
                size="sm" 
                onClick={() => copyToClipboard(seed.toString(), "seed")}
              >
                {copiedCode === "seed" ? <Check className="w-4 h-4" /> : <Copy className="w-4 h-4" />}
              </Button>
            </div>
          </div>
        </div>

        {/* Export Options */}
        <div className="flex items-center gap-4">
          <div className="flex items-center gap-2">
            <Switch checked={includeRawData} onCheckedChange={setIncludeRawData} id="raw" />
            <Label htmlFor="raw" className="text-xs">Include raw data</Label>
          </div>
          <div className="flex items-center gap-2">
            <Switch checked={includeMetadata} onCheckedChange={setIncludeMetadata} id="meta" />
            <Label htmlFor="meta" className="text-xs">Include metadata</Label>
          </div>
        </div>

        {/* Export Tabs */}
        <Tabs defaultValue="csv" className="space-y-3">
          <TabsList className="grid w-full grid-cols-4 h-9">
            <TabsTrigger value="csv" className="text-xs gap-1">
              <FileSpreadsheet className="w-3 h-3" />
              CSV
            </TabsTrigger>
            <TabsTrigger value="json" className="text-xs gap-1">
              <FileJson className="w-3 h-3" />
              JSON
            </TabsTrigger>
            <TabsTrigger value="python" className="text-xs gap-1">
              <Code2 className="w-3 h-3" />
              Python
            </TabsTrigger>
            <TabsTrigger value="r" className="text-xs gap-1">
              <BookOpen className="w-3 h-3" />
              R
            </TabsTrigger>
          </TabsList>

          <TabsContent value="csv" className="space-y-3">
            <ScrollArea className="h-32 rounded-lg bg-foreground/5 p-3 font-mono text-xs">
              <pre className="text-foreground/70">{generateCSV().slice(0, 500)}...</pre>
            </ScrollArea>
            <div className="flex gap-2">
              <Button 
                size="sm" 
                className="flex-1 gap-2"
                onClick={() => downloadFile(generateCSV(), `openworm_sim_${seed}.csv`, "text/csv")}
              >
                <Download className="w-4 h-4" />
                Download CSV
              </Button>
              <Button 
                size="sm" 
                variant="outline"
                onClick={() => copyToClipboard(generateCSV(), "csv")}
              >
                {copiedCode === "csv" ? <Check className="w-4 h-4" /> : <Copy className="w-4 h-4" />}
              </Button>
            </div>
          </TabsContent>

          <TabsContent value="json" className="space-y-3">
            <ScrollArea className="h-32 rounded-lg bg-foreground/5 p-3 font-mono text-xs">
              <pre className="text-foreground/70">{generateJSON().slice(0, 600)}...</pre>
            </ScrollArea>
            <div className="flex gap-2">
              <Button 
                size="sm" 
                className="flex-1 gap-2"
                onClick={() => downloadFile(generateJSON(), `openworm_sim_${seed}.json`, "application/json")}
              >
                <Download className="w-4 h-4" />
                Download JSON
              </Button>
              <Button 
                size="sm" 
                variant="outline"
                onClick={() => copyToClipboard(generateJSON(), "json")}
              >
                {copiedCode === "json" ? <Check className="w-4 h-4" /> : <Copy className="w-4 h-4" />}
              </Button>
            </div>
          </TabsContent>

          <TabsContent value="python" className="space-y-3">
            <ScrollArea className="h-32 rounded-lg bg-foreground/5 p-3 font-mono text-xs">
              <pre className="text-foreground/70">{generatePythonNotebook().slice(0, 600)}...</pre>
            </ScrollArea>
            <div className="flex gap-2">
              <Button 
                size="sm" 
                className="flex-1 gap-2"
                onClick={() => downloadFile(generatePythonNotebook(), `openworm_analysis_${seed}.py`, "text/x-python")}
              >
                <Download className="w-4 h-4" />
                Download .py
              </Button>
              <Button 
                size="sm" 
                variant="outline"
                onClick={() => copyToClipboard(generatePythonNotebook(), "python")}
              >
                {copiedCode === "python" ? <Check className="w-4 h-4" /> : <Copy className="w-4 h-4" />}
              </Button>
            </div>
            <p className="text-xs text-muted-foreground flex items-center gap-1">
              <ExternalLink className="w-3 h-3" />
              Compatible with Jupyter Notebook, Google Colab, and VS Code
            </p>
          </TabsContent>

          <TabsContent value="r" className="space-y-3">
            <ScrollArea className="h-32 rounded-lg bg-foreground/5 p-3 font-mono text-xs">
              <pre className="text-foreground/70">{generateRScript().slice(0, 500)}...</pre>
            </ScrollArea>
            <div className="flex gap-2">
              <Button 
                size="sm" 
                className="flex-1 gap-2"
                onClick={() => downloadFile(generateRScript(), `openworm_analysis_${seed}.R`, "text/x-r")}
              >
                <Download className="w-4 h-4" />
                Download .R
              </Button>
              <Button 
                size="sm" 
                variant="outline"
                onClick={() => copyToClipboard(generateRScript(), "r")}
              >
                {copiedCode === "r" ? <Check className="w-4 h-4" /> : <Copy className="w-4 h-4" />}
              </Button>
            </div>
          </TabsContent>
        </Tabs>

        {/* Citation Generator */}
        <div className="p-3 bg-primary/5 rounded-lg border border-primary/20">
          <Label className="text-xs font-bold flex items-center gap-2 mb-2">
            <BookOpen className="w-4 h-4 text-primary" />
            Suggested Citation
          </Label>
          <p className="text-xs text-muted-foreground font-mono">
            OpenWorm Project. (2024). WormQuest Neural Simulation Platform. 
            Simulation seed: {seed}. Retrieved from https://openworm.org
          </p>
          <Button 
            variant="ghost" 
            size="sm" 
            className="mt-2 text-xs"
            onClick={() => copyToClipboard(
              `OpenWorm Project. (2024). WormQuest Neural Simulation Platform. Simulation seed: ${seed}. Retrieved from https://openworm.org`,
              "citation"
            )}
          >
            {copiedCode === "citation" ? <Check className="w-3 h-3 mr-1" /> : <Copy className="w-3 h-3 mr-1" />}
            Copy Citation
          </Button>
        </div>
      </CardContent>
    </Card>
  );
}
